[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Aquarius ONE SDK"
authors = [{name = "Graziella", email = "steve.wood@aquaticinformatics.com"}]
dynamic = ["version", "description"]
