namespace ONE.ClientSDK.Enums
{
	public enum EnumErrors
	{
		ERR_UNKNOWN = 0,
		ERR_NOT_SUPPORTED = 1,
		ERR_INVALID_VALUE = 2,
		ERR_INVALID_TYPE = 3,
		ERR_INVALID_FORMAT = 4,
		ERR_INVALID_OPERATION_GUID = 5,
		ERR_OPERATION_NOT_LOADED = 6,
		ERR_INVALID_PARAMETER_GUID = 7,
		ERR_INDEX_OUT_OF_RANGE = 8,
		ERR_INVALID_DATE = 9,
		ERR_NOT_AUTHENTICATED = 10,
		ERR_NOT_IMPLEMENTED = 11,
		ERR_INVALID_PARAMETER_IDENTIFIER = 12,
		ERR_INVALID_QUALIFIER_RULE = 13,
		ERR_INVALID_CASCADE_RULE = 14,
		ERR_DEPRECATED = 15
	}
}
